Repository viky-ai/website, pull requests merged in 2019-12, with the labels that each got.

#1 Feature/20994 interpretations entities doc
  blog/_posts/2019-12-02-viky-ai-available-in-open-source/2019-12-02-viky-ai-available-in-open-source.md
  doc/how-to/discover-and-try-agents/index.md
  doc/how-to/import-export-entities/index.md
  doc/how-to/know-why-an-interpretation-match/index.md
  doc/how-to/make-non-regression-tests/index.md
  doc/how-to/match-unknown-words/index.md
  doc/how-to/work-collaboratively/index.md
  doc/how-to/work-with-internationalization/index.md
  doc/topics/agent/index.md
  doc/topics/interpretation/img/01_change_temperature.png
  doc/topics/interpretation/img/02_change_temperature.png
  doc/topics/interpretation/img/03_change_temperature.png
  doc/topics/interpretation/img/04_change_temperature.png
  doc/topics/interpretation/index.md
  doc/topics/main-concepts-behind-viky-ai/index.md
Labels: documentation

#6 Add project founders section to press kit
  about/press-kit/charles-henri-puaux.jpg
  about/press-kit/index.html
  about/press-kit/patrick-constant.jpg
  site_assets/css/_press_kit.scss
Labels: documentation

#8 Deploy project founders section to press kit.
  about/press-kit/charles-henri-puaux.jpg
  about/press-kit/index.html
  about/press-kit/patrick-constant.jpg
  site_assets/css/_press_kit.scss
Labels: documentation

#10 [fixed] Deploy env name
  .gitlab-ci.yml
Labels: deployment

#11 [changed] Deploy : Use env name instead of env slug
  .gitlab-ci.yml
Labels: deployment

#5 Blog post: Voice Tech Paris Recap
  blog/_posts/2019-12-05-voice-tech-paris-recap/2019-12-05-voice-tech-paris-recap.md
  blog/_posts/2019-12-05-voice-tech-paris-recap/patrick_constant_voice_tech_paris.jpg
  blog/_posts/2019-12-05-voice-tech-paris-recap/social.jpg
Labels: documentation

#14 Deploy Saas : Analytics with Matomo
  .dockerignore
  _config.yml
  _includes/analytics.html
  _layouts/default.html
  _layouts/error.html
  about/privacy-policy/index.md
  deployment/nginx/nginx.conf
Labels: deployment

#17 Set pull request template as default
  .github/pull_request_template.md
Labels: bug

#19 Sync SaaS
  .github/pull_request_template.md
  _includes/analytics.html
Labels: deployment

#21 #21768 [changed] Doc, explain force language change
  doc/reference/agents-api/index.md
Labels: documentation

#22 Sync SaaS
  doc/reference/agents-api/index.md
Labels: deployment

#20 #missing [change] Deploy : full deploy of dev branches become manual
  .gitlab-ci.yml
Labels: deployment

#15 Agent Numbers
  .gitignore
  blog/_posts/2019-12-17-agent-number/2019-12-17-agent-numbers.md
  blog/_posts/2019-12-17-agent-number/agent_numbers.jpg
  blog/_posts/2019-12-17-agent-number/social.jpg
Labels: documentation

#29 Sync SaaS branch
  pricing/index.html
Labels: deployment
